# Generated by Django 6.0.6 on 2026-07-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiTenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
