# Generated by Django 6.0.6 on 2026-07-04 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiTenants', '0002_tenants_plan_tenants_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='domain',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
