# Generated by Django 6.0.6 on 2026-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiTenants', '0003_alter_tenants_client_uuid_alter_tenants_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
